/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Предстоящие встречи: единый список бронирований всех типов событий */
        get: operations["AdminBookings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Просмотр созданных типов событий */
        get: operations["AdminEventTypes_list"];
        put?: never;
        /** @description Создание типа события владельцем */
        post: operations["AdminEventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Просмотр одного типа события */
        get: operations["AdminEventTypes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Создание бронирования на свободный слот. 201 — бронь создана, 409 — слот занят */
        post: operations["GuestBookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список видов брони: название, описание и длительность */
        get: operations["GuestEventTypes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Свободные слоты типа события в 14-дневном окне от текущей даты */
        get: operations["GuestEventTypes_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Расписание предстоящих встреч, видимое гостю */
        get: operations["GuestMeetings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Ошибка 400: невалидные входные данные или startAt вне окна записи */
        BadRequestError: {
            /** @enum {string} */
            code: "bad_request";
            message: string;
        };
        /** @description Бронирование: гость записывается на слот без аккаунта, оставляя имя. */
        Booking: {
            /** @description Уникальный идентификатор бронирования */
            id: string;
            /** @description Тип события, на который записан гость */
            eventTypeId: string;
            /** @description Имя гостя */
            guestName: string;
            /**
             * Format: date-time
             * @description Начало встречи в формате UTC
             */
            startAt: string;
            /**
             * Format: date-time
             * @description Конец встречи, вычисляется из длительности типа события
             */
            endAt: string;
        };
        /** @description Данные для создания бронирования гостем */
        BookingCreate: {
            /** @description Тип события, на который записывается гость */
            eventTypeId: string;
            /** @description Имя гостя, непустая строка */
            guestName: string;
            /**
             * Format: date-time
             * @description Начало встречи в формате UTC, внутри 14-дневного окна записи
             */
            startAt: string;
        };
        /** @description Ошибка 409: слот занят другой записью любого типа события */
        ConflictError: {
            /** @enum {string} */
            code: "slot_conflict";
            message: string;
        };
        /**
         * @description Тип события: вид записи, который создаёт владелец.
         *     Название, описание и длительность видны гостю на странице видов брони.
         */
        EventType: {
            /** @description Уникальный идентификатор типа события */
            id: string;
            /** @description Название, видимое гостю */
            name: string;
            /** @description Описание, видимое гостю */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах, строго больше нуля
             */
            durationMinutes: number;
        };
        /** @description Данные для создания тип события владельцем */
        EventTypeCreate: {
            /** @description Название, видимое гостю */
            name: string;
            /** @description Описание, видимое гостю */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах, строго больше нуля
             */
            durationMinutes: number;
        };
        /** @description Ошибка 404: тип события не найден */
        NotFoundError: {
            /** @enum {string} */
            code: "not_found";
            message: string;
        };
        /** @description Единственный предзаданный профиль владельца календаря */
        Owner: {
            /**
             * @description Идентификатор владельца, заранее заданный и неизменный
             * @enum {string}
             */
            id: "default-owner";
            /** @description Отображаемое имя владельца */
            name: string;
        };
        /**
         * @description Свободный слот: вычисляемое значение, не хранится.
         *     Формируется из длительности типа события (шаг 30 минут, 24/7) без учёта
         *     рабочих часов. Слот свободен, если на интервал [startAt, endAt) нет
         *     ни одного бронирования — любого типа события.
         */
        Slot: {
            /** @description Тип события, для которого рассчитан слот */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало слота в формате UTC
             */
            startAt: string;
            /**
             * Format: date-time
             * @description Конец слота, вычисляется как startAt + длительность типа события
             */
            endAt: string;
            /** @description Признак свободного слота */
            available: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminBookings_list: {
        parameters: {
            query?: {
                /** @description Показать встречи, начиная с этого времени. Не задано — текущее время */
                from?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    AdminEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    AdminEventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ошибка 400: невалидные входные данные или startAt вне окна записи */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
        };
    };
    AdminEventTypes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ошибка 404: тип события не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    GuestBookings_create: {
        parameters: {
            query?: never;
            header: {
                accept: "application/json";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Успешное создание бронирования: тело — созданная запись */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Ошибка 400: невалидные входные данные или startAt вне окна записи */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description Ошибка 404: тип события не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description Ошибка 409: слот занят другой записью любого типа события */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
        };
    };
    GuestEventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    GuestEventTypes_listSlots: {
        parameters: {
            query?: {
                /** @description Начало интервала выборки. Не задано — берётся текущая дата (окно записи 14 дней) */
                from?: string;
                /** @description Конец интервала выборки. Не задано — берётся текущая дата + 14 дней */
                to?: string;
            };
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description Ошибка 404: тип события не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    GuestMeetings_list: {
        parameters: {
            query?: {
                /** @description Показать встречи, начиная с этого времени. Не задано — текущее время */
                from?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
}
